### PR TITLE
Fix API key

### PR DESCRIPTION
**Pull request by mgroeneweg**
Ported Jelte's change to my geolocation widget to the official
GoogleMaps widget. Also upgraded test project to Mendix 5.21
This fixes issue #5

### CODE REVIEW

**Comment by JelteMX** [comment]
Great :smile:! Will test it tomorrow and create a new release for the AppStore.

**Comment by mgroeneweg** [comment]
The Check Widgets tool rejects the widget! Can be seen in the test project.

**Comment by JelteMX** [comment]
Yeah I got your e-mail. No worries. We'll look into it tomorrow.

**Comment by JelteMX** [comment]
Checked the problem and it seems require cannot handle the external url. That is, it will work locally (because widgets are loaded separately). Unfortunately, when you want to deploy, the Modeler will check all the required libraries and bundles them in 1 single JS. I'll ask if there is a way to reference to an external library using require.. 

In the meantime, I think we need to copy Google's jsapi.js to our lib folder and include it locally. That seems to work (with the API key as well, tested it). I'll include this in the next release and will provide a pull request for your widget as well.

**Comment by JelteMX** [comment]
I rewrote the [fix I used on your widget](https://github.com/mgroeneweg/mendix-GeoLocationWidget/pull/5) and applied it on this widget as well. Will submit a new version to the AppStore

**Pull request closed without merging**
